vich_uploader:
    db_driver: orm

    mappings:
        post_images:
            uri_prefix: /uploads/post_images/
            upload_destination: '%kernel.project_dir%/public/uploads/post_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
