version: "3.1"
services:
  php:
    build: ./docker/php
    container_name: ${PROJECT_NAME}-php
    volumes:
      - .:/var/www/html
      - ./docker/php/php-ini-overrides.ini:/etc/php/8.1.1/fpm/conf.d/99-overrides.ini
    ports:
      - "9002:9002"
    env_file:
    - ./docker/.env
    restart: always
    networks:
      - dev

  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-nginx
    depends_on:
      - php
    volumes:
        - .:/var/www/html
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - .:/mysql/data
    ports:
      - "80:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rnm-api.rule=Host(`dev.sblog.local`)"
      - "traefik.http.routers.rnm-api.entrypoints=websecure"
      - "traefik.http.routers.rnm-api.tls.certresolver=myresolver"
    env_file:
    - ./docker/.env
    restart: always
    networks:
      - dev

networks:
  dev: